# Generated by Django 5.0.6 on 2025-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_time', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, upload_to='recipe_images/')),
                ('ingredients', models.TextField()),
                ('ingredient_quantities', models.TextField()),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('servings', models.BigIntegerField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
